version: '3.8'

services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: listeny
      MYSQL_USER: alejandro
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql

  app:
    build: ./
    restart: on-failure
    ports:
      - "8091:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
